services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf 
      - ./data:/mosquitto/data 
      - ./log:/mosquitto/log 
